#!/bin/bash
mkdir -p stitch_assets

# 1. Refined Operational Monitor
curl -L -o stitch_assets/refined_operational_monitor.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzBiNmYwMTJiYTQ0ODRkNTJiN2U0ZDYwZWVjNDY5ZmQ3EgsSBxDIt-S3hw8YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzYzMTcyMzEwOTc4NDA0OTQ0MA&filename=&opi=89354086"
curl -L -o stitch_assets/refined_operational_monitor_screenshot.png "https://lh3.googleusercontent.com/aida/AOfcidUf_JzmrcZqIODK_3o7a0_G0hvqqe_WvVcLOtll722XLJZgkQSraX9jeWt4Auj3NhCm-tMzzoe1OuXdXg2N2O47OipY-lWnIeo3wLBhWZyhRPg7gJlxfoZCxTzrJ3UqHVpSP3jfDFgpJb9_XbW_h-BKcl4CAQzmWbXxB4GKtovE0ZqUwHpx5FGZU5Wut1FBz3SWB2CG4Mi9rDGpfS3iEy-8CeJ8fvhwVq3AOhHtV7l_1-z2WkmdrHM5PWCg"

# 2. Refined RAG Calibration Console
curl -L -o stitch_assets/refined_rag_calibration_console.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzVhZDNlYzBiNWFhNDQxNGY5ZDgzOWFhOWZjZmMyMDkzEgsSBxDIt-S3hw8YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzYzMTcyMzEwOTc4NDA0OTQ0MA&filename=&opi=89354086"
curl -L -o stitch_assets/refined_rag_calibration_console_screenshot.png "https://lh3.googleusercontent.com/aida/AOfcidWyieGyFp8aqKypvgIbwA89rD8jYq-CkNORWbVXYFD4imOed-2OryHjOXnSAsolUY44mpsELE1fE24HIEsGZ2fOl26ziRF-qOcNyQD7NM5iH2dR0XvSN6ckTBptOt75pC3ZlHRGmWt9jFVHqi07XfKeKhtNl3LrDRD73pdqKS1hrzlJT4R1zJpvm9XVNq0vPPFdyR4w0SX-pRDUhD0I0Mo9nmbSpw8D8yV1Cd6bcvqkWIc3UXb7Mx3svJU8"

# 3. Refined Vector Inspector
curl -L -o stitch_assets/refined_vector_inspector.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2VmYTY3YzZkZGNlZjQ4MGVhNDZhNTU2ZWFjNjRhZmU1EgsSBxDIt-S3hw8YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzYzMTcyMzEwOTc4NDA0OTQ0MA&filename=&opi=89354086"
curl -L -o stitch_assets/refined_vector_inspector_screenshot.png "https://lh3.googleusercontent.com/aida/AOfcidVgAXq7JxYdUPrRJPw3iQMmkpCFFed-1S1dBnX07IogJ46kWXU5KJSPuRSMqNBb5YFQ8ZeIzg3MFB7JYP-IRuDzcl01_722BQWrHcrclRYUxvQLjaqNN7UBdEjVynaCxt-QZFlT65XOwW-kIcbhAKC72ASTiFRPq7pQAB8ch-UABaqAio9a1sPjHFUuMLENOS8yW6xy_AlpHrlmY75M_Yj4lC_9gnEMjPOhoaZv_cloZVqfuBUaqYW_u4YA"

# 4. Refined Pipeline Configuration
curl -L -o stitch_assets/refined_pipeline_configuration.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzBkYWQ1YjM0YWMzZTQ3OWM4NTBiZjcxOTI3OWExNjFhEgsSBxDIt-S3hw8YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzYzMTcyMzEwOTc4NDA0OTQ0MA&filename=&opi=89354086"
curl -L -o stitch_assets/refined_pipeline_configuration_screenshot.png "https://lh3.googleusercontent.com/aida/AOfcidUkP0L_F3Zsuv2QAbwrLUIxCF8iKFUsZQtqBrWsxDrpe_gjgdsk7AGA40oCUEwN6evvPN_yi1hi3e9h8uC2MJJVPkrsKUzch_2lvhnAuk70qWCBySQV81xHolrx-M86ht1IE45LXwzRl-MB3Jgst-9HZLKLitfPHSI_RNtg1mURE3vHmJeUgwxi8CM2draQBXq7a9PT_e2gPV-BWmstGiPjBJtBiQ5Uve9SsyFvCxQUk0LSMGCooe0J4IUA"

# 5. Refined 05 Topology
curl -L -o stitch_assets/refined_05_topology.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzdkYjlkYTMzMjY4ZTQyMDM4M2U0OWEzYmJhZjQ1ZmM0EgsSBxDIt-S3hw8YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzYzMTcyMzEwOTc4NDA0OTQ0MA&filename=&opi=89354086"
curl -L -o stitch_assets/refined_05_topology_screenshot.png "https://lh3.googleusercontent.com/aida/AOfcidXkyRFboIT7TF20hU83VG8b1cXXGyVaRPsYdqYQ8Ne9XHI916BDKe_F39zWW8LIPQXypAoNxeL72-RAbOEJiugeDLI-IUtA_GyVhmnQ5dLWM-Am-NFlLKtqRsYsMbLeymN8ynqTHcwQNAgquN36ZwQ3flEC4M8m8Y4N1wvu20iY8tEK2BEeGuBLsDwB4CKqIs8HvWxaLyfRdEs_T7q2lK1F-noWsFOTYCdTx_y-gT8CIHJHtM33SsK8feU"

# 6. Swiss System Integration Guide
curl -L -o stitch_assets/swiss_system_integration_guide.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzI4MTUxNDU5NjIyYjRiYTZiYmQyY2FiNjJmZmQwOGM0EgsSBxDIt-S3hw8YAZIBJAoKcHJvamVjdF9pZBIWQhQxMzYzMTcyMzEwOTc4NDA0OTQ0MA&filename=&opi=89354086"
curl -L -o stitch_assets/swiss_system_integration_guide_screenshot.png "https://lh3.googleusercontent.com/aida/AOfcidV9J9JK63L2g4H-2XFWG_zlTEFQ9YTtNCMGrRGB86cnP7-zk0wPowzP5F26Vph2rT_1JUQ3apltuwApEY_OSA6fvdG-PZLzqBV34bQksc_GuVTG7MvGcjLt06hdvTGbyJS1bKXugEtr9mMhPmJz3kGxDH92mBDmwZpUbZr6znPj-L8VqkAtDjKfI7Nubzh7i8SzWAxf_06mDTh6eD152W8Q98dM5mgC2htoYoEX2Zv5vwgn85v60awbs2ri"

echo "Download completed."
